"""yeni veritabanı

Revision ID: f416773e728a
Revises: 
Create Date: 2024-07-12 16:56:21.719629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f416773e728a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_adi', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('parola_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kullanici_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_kullanici_kullanici_adi'), ['kullanici_adi'], unique=True)

    op.create_table('urun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isim', sa.String(length=100), nullable=True),
    sa.Column('aciklama', sa.String(length=500), nullable=True),
    sa.Column('fotograf', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('urun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_urun_isim'), ['isim'], unique=False)

    op.create_table('inceleme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icerik', sa.String(length=500), nullable=True),
    sa.Column('puan', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('urun_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanici.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inceleme', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inceleme_tarih'), ['tarih'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inceleme', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inceleme_tarih'))

    op.drop_table('inceleme')
    with op.batch_alter_table('urun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_urun_isim'))

    op.drop_table('urun')
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kullanici_kullanici_adi'))
        batch_op.drop_index(batch_op.f('ix_kullanici_email'))

    op.drop_table('kullanici')
    # ### end Alembic commands ###
